# Name: Flexoki Dark
# URL: https://stephango.com/flexoki

set -g status on
set -g status-bg "#1c1b1a"
set -g status-justify left
set -g status-left-length 80
set -g status-right-length 120

set -g message-style "fg=#cecdc3,bg=#282726"
set -g message-command-style "fg=#cecdc3,bg=#1c1b1a"

set -g pane-border-style "fg=#282726"
set -g pane-active-border-style "fg=#4385be"

set -g window-status-separator ""
set -g window-status-style "fg=#878580,bg=#1c1b1a"
set -g window-status-activity-style "fg=#da702c,bg=#1c1b1a"

set -g clock-mode-colour "#4385be"
set -g mode-style "fg=#100f0f,bg=#da702c,bold"

set -g status-left "#{?client_prefix,#[fg=#100f0f]#[bg=#d14d41]#[bold] #S #[fg=#d14d41]#[bg=#1c1b1a]#[nobold],#[fg=#100f0f]#[bg=#879a39]#[bold] #S #[fg=#879a39]#[bg=#1c1b1a]#[nobold]}#{?window_zoomed_flag,#[fg=#d0a215]#[bg=#1c1b1a]  ,} "
set -g status-right "#[fg=#282726]#[bg=#1c1b1a]#[fg=#878580]#[bg=#282726] #{b:pane_current_path} #[fg=#4385be]#[bg=#282726]#[fg=#1c1b1a]#[bg=#4385be]#[bold] %H:%M #[fg=#8b7ec8]#[bg=#4385be]#[fg=#1c1b1a]#[bg=#8b7ec8]#[bold] %d %b "
setw -g window-status-format "#[fg=#1c1b1a]#[bg=#282726]#[fg=#878580]#[bg=#282726] #I  #W #[fg=#282726]#[bg=#1c1b1a]"
setw -g window-status-current-format "#[fg=#1c1b1a]#[bg=#d0a215]#[fg=#100f0f]#[bg=#d0a215]#[bold] #I  #W #[fg=#d0a215]#[bg=#1c1b1a]#[nobold]"
