# Name: Dracula
# URL: https://draculatheme.com/tmux

set -g status on
set -g status-bg "#282a36"
set -g status-justify left
set -g status-left-length 80
set -g status-right-length 120

set -g message-style "fg=#f8f8f2,bg=#44475a"
set -g message-command-style "fg=#f8f8f2,bg=#282a36"

set -g pane-border-style "fg=#44475a"
set -g pane-active-border-style "fg=#bd93f9"

set -g window-status-separator ""
set -g window-status-style "fg=#6272a4,bg=#282a36"
set -g window-status-activity-style "fg=#ffb86c,bg=#282a36"

set -g clock-mode-colour "#bd93f9"
set -g mode-style "fg=#282a36,bg=#ffb86c,bold"

set -g status-left "#{?client_prefix,#[fg=#282a36]#[bg=#ff5555]#[bold] #S #[fg=#ff5555]#[bg=#282a36]#[nobold],#[fg=#282a36]#[bg=#50fa7b]#[bold] #S #[fg=#50fa7b]#[bg=#282a36]#[nobold]}#{?window_zoomed_flag,#[fg=#f1fa8c]#[bg=#282a36]  ,} "
set -g status-right "#[fg=#44475a]#[bg=#282a36]#[fg=#6272a4]#[bg=#44475a] #{b:pane_current_path} #[fg=#bd93f9]#[bg=#44475a]#[fg=#282a36]#[bg=#bd93f9]#[bold] %H:%M #[fg=#ff79c6]#[bg=#bd93f9]#[fg=#282a36]#[bg=#ff79c6]#[bold] %d %b "
setw -g window-status-format "#[fg=#282a36]#[bg=#44475a]#[fg=#6272a4]#[bg=#44475a] #I  #W #[fg=#44475a]#[bg=#282a36]"
setw -g window-status-current-format "#[fg=#282a36]#[bg=#f1fa8c]#[fg=#282a36]#[bg=#f1fa8c]#[bold] #I  #W #[fg=#f1fa8c]#[bg=#282a36]#[nobold]"
