## name: Dracula

# The basic colors.
foreground              #F8F8F2
background              #282A36
selection_foreground    #FFFFFF
selection_background    #44475A

# Cursor colors.
cursor                  #F8F8F2
cursor_text_color       background

# kitty window border colors.
active_border_color     #F8F8F2
inactive_border_color   #6272A4

# Tab bar colors.
active_tab_foreground   #282A36
active_tab_background   #F8F8F2
inactive_tab_foreground #282A36
inactive_tab_background #6272A4

# URL color.
url_color #8BE9FD

# The basic 16 colors.

# Black.
color0 #21222C
color8 #6272A4

# Red.
color1 #FF5555
color9 #FF6E6E

# Green.
color2  #50FA7B
color10 #69FF94

# Yellow.
color3  #F1FA8C
color11 #FFFFA5

# Blue.
color4  #BD93F9
color12 #D6ACFF

# Magenta.
color5  #FF79C6
color13 #FF92DF

# Cyan.
color6  #8BE9FD
color14 #A4FFFF

# White.
color7  #F8F8F2
color15 #FFFFFF
