# Theme (flexoki_dark)
include themes/flexoki_dark.conf

# Font
font_family      JetBrainsMono Nerd Font
font_size        12.5
bold_font        auto
italic_font      auto
bold_italic_font auto

# Ligatures
disable_ligatures never

# Terminal
term              xterm-kitty
enable_audio_bell no

# UI
background_opacity   0.90
tab_bar_style        hidden
window_padding_width 8 12

# Cursor
cursor_shape          beam
cursor_blink_interval 0
cursor_text_color     background
cursor                #879a39

# URL
url_color    #4385be
url_style     straight
open_url_with default
detect_urls   yes

# Selection
highlight_url_on_hover yes
copy_on_select         no

# Marks (flexoki accent colors)
mark1_foreground #100f0f
mark1_background #879a39
mark2_foreground #100f0f
mark2_background #4385be
mark3_foreground #100f0f
mark3_background #ce5d97

# Scrollback
scrollback_lines              100000
scrollback_pager_history_size 0

# Mouse
mouse_hide_wait     2.0
focus_follows_mouse no

# Window
remember_window_size  yes
initial_window_width  220c
initial_window_height 50c
