# Theme (rose-pine).
include themes/gruvbox_dark.conf

# Font.
font_family JetBrainsMono Nerd Font
font_size 12.5

# UI.
background_opacity 0.85
tab_bar_style hidden

# Padding.
window_padding_width 0

# Behavior.
enable_audio_bell no
