# Theme (dracula)
include themes/dracula.conf

# Font
font_family      JetBrainsMono Nerd Font
font_size        12.5
bold_font        auto
italic_font      auto
bold_italic_font auto

# Ligatures
disable_ligatures never

# Terminal
term              xterm-kitty
enable_audio_bell no

# UI
background_opacity   0.90
tab_bar_style        hidden
window_padding_width 8 12

# Cursor
cursor_shape          beam
cursor_blink_interval 0
cursor_text_color     background
cursor                #50fa7b

# URL
url_style     straight
open_url_with default
detect_urls   yes

# Selection
highlight_url_on_hover yes
copy_on_select         no

# Marks (dracula accent colors)
mark1_foreground #282a36
mark1_background #50fa7b
mark2_foreground #282a36
mark2_background #bd93f9
mark3_foreground #282a36
mark3_background #ff79c6

# Scrollback
scrollback_lines              100000
scrollback_pager_history_size 0

# Mouse
mouse_hide_wait     2.0
focus_follows_mouse no

# Window
remember_window_size  yes
initial_window_width  220c
initial_window_height 50c
